In [ ]:
a=["apple","banana","cherry"]

In [ ]:
a.append("bread")
a

['apple', 'banana', 'cherry', 'bread']

In [ ]:
a.remove("banana")
a

['apple', 'cherry', 'bread']

In [ ]:
"cherry" in a

True

In [ ]:
len(a)

3

In [ ]:
tuple=(120,"abcd",786,0.2,'john')
print(tuple)
print(tuple[0])
print(tuple[1:3])
print(tuple[2:])
print(tuple * 2)

(120, 'abcd', 786, 0.2, 'john')
120
('abcd', 786)
(786, 0.2, 'john')
(120, 'abcd', 786, 0.2, 'john', 120, 'abcd', 786, 0.2, 'john')


In [ ]:
students = [
    ("Alice", [85, 78, 92]),
    ("Bob", [66, 74, 81]),
    ("Charlie", [90, 88, 85])
]

In [ ]:
for i,j in students:
  avg=sum(j)/len(j)
  print(i,avg)


Alice 85.0
Bob 73.66666666666667
Charlie 87.66666666666667


In [ ]:
highavg=0
topper=""
for i in students:
  name = i[0]
  marks = i[1]
  avg=sum(marks)/len(marks)
  if avg>highavg:
    highavg=avg
    topper=name
print(topper,highavg)

Charlie 87.66666666666667


In [ ]:
students.append(("David", [70, 75, 80]))

In [ ]:
for i in range(len(students)):
    if students[i][0] == "Bob":
        students[i][1][1] = 79
        break

In [ ]:
for i in students:
    print(i)

('Alice', [85, 78, 92])
('Bob', [66, 79, 81])
('Charlie', [90, 88, 85])
('David', [70, 75, 80])


In [ ]:
dict={}
type(dict)

dict

In [ ]:
web={'day':1,'visitors':20,'bounce':10}
web

{'day': 1, 'visitors': 20, 'bounce': 10}

In [ ]:
print(web.keys())

dict_keys(['day', 'visitors', 'bounce'])


In [ ]:
print(web.values())

dict_values([1, 20, 10])


In [ ]:
web.items()

dict_items([('day', 1), ('visitors', 20), ('bounce', 10)])

In [ ]:
# prompt: more functions of set

set1 = {"apple", "banana", "cherry"}
set2 = {"google", "microsoft", "apple"}

# Union of sets
set3 = set1.union(set2)
print("Union:", set3)

# Intersection of sets
set4 = set1.intersection(set2)
print("Intersection:", set4)

# Difference of sets (elements in set1 but not in set2)
set5 = set1.difference(set2)
print("Difference (set1 - set2):", set5)

# Symmetric difference of sets (elements in either set but not in both)
set6 = set1.symmetric_difference(set2)
print("Symmetric difference:", set6)

# Adding elements to a set
set1.add("orange")
print("After adding orange:", set1)

# Removing elements from a set (discards error if element is not present)
set1.discard("banana")
print("After discarding banana:", set1)

# Removing elements from a set (raises error if element is not present)
try:
    set1.remove("kiwi")
except KeyError:
    print("Cannot remove 'kiwi' as it's not in the set.")

# Check if a set is a subset of another set
print("Is set1 a subset of set3?", set1.issubset(set3))

# Check if a set is a superset of another set
print("Is set3 a superset of set1?", set3.issuperset(set1))

# Pop an arbitrary element from the set
popped_element = set1.pop()
print("Popped element:", popped_element)
print("Set after pop:", set1)

# Clear all elements from a set
set1.clear()
print("Set after clear:", set1)

# Delete a set
# del set1
# print(set1) # This would raise a NameError as the set is deleted

Union: {'google', 'apple', 'microsoft', 'cherry', 'banana'}
Intersection: {'apple'}
Difference (set1 - set2): {'cherry', 'banana'}
Symmetric difference: {'google', 'microsoft', 'cherry', 'banana'}
After adding orange: {'apple', 'cherry', 'banana', 'orange'}
After discarding banana: {'apple', 'cherry', 'orange'}
Cannot remove 'kiwi' as it's not in the set.
Is set1 a subset of set3? False
Is set3 a superset of set1? False
Popped element: apple
Set after pop: {'cherry', 'orange'}
Set after clear: set()


In [ ]:
for i in range(10):
  print(f'2*{i+1}={2*i+1}')

2*1=1
2*2=3
2*3=5
2*4=7
2*5=9
2*6=11
2*7=13
2*8=15
2*9=17
2*10=19


In [ ]:
a=["mango","apple","banana"]
for i in a:
  print(i,end=" | ")

mango | apple | banana | 

In [ ]:
a=int(input("Enter 1st no:"))
b=int(input("Enter 2nd no:"))
while True:
  opr=input("Enter the opeator:")
  if opr=='+':
    print(a+b)
  elif opr=='-':
    print(a-b)
  elif opr=='*':
    print(a*b)
  elif opr=='/':
    print(a/b)
  else:
    print("Enter valid choice!!!")
    break

Enter 1st no:10
Enter 2nd no:9
Enter the opeator:+
19
Enter the opeator:-
1
Enter the opeator:/
1.1111111111111112
Enter the opeator:*
90
Enter the opeator:o
Enter valid choice!!!


In [ ]:
import numpy as np

In [ ]:
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
a.shape

(2, 2, 2)

In [ ]:
np.reshape(a,(4,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.reshape(a,(1,8))

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [ ]:
np.reshape(a,(8,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])