In [ ]:
import numpy as np
l=[2,3,4,5]
k=[4,5,6,3]
type(l)

list

In [ ]:
n=np.array([l,k])
n

array([[2, 3, 4, 5],
       [4, 5, 6, 3]])

In [ ]:
np.ndim(n)

2

In [ ]:
narray=np.array([[3,4,5,6],[5,6,7,4]])
narray

array([[3, 4, 5, 6],
       [5, 6, 7, 4]])

In [ ]:
np.shape(narray)

(2, 4)

In [ ]:
#Numpy Functions
na=np.array([[4,5,6,7],[5,6,7,4]])
na


array([[4, 5, 6, 7],
       [5, 6, 7, 4]])

In [ ]:
np.shape(na)

(2, 4)

In [ ]:
#reshape
np.reshape(na,(4,2))

array([[4, 5],
       [6, 7],
       [5, 6],
       [7, 4]])

In [ ]:
np.reshape(na,(1,8))

array([[4, 5, 6, 7, 5, 6, 7, 4]])

In [ ]:
np.reshape(na,(8,1))

array([[4],
       [5],
       [6],
       [7],
       [5],
       [6],
       [7],
       [4]])

In [ ]:
a=np.arange(1,11,2).reshape(5,1)
a

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [ ]:
#linspace
b=np.linspace(1,10,10).reshape(5,2)
b

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

In [ ]:
np.sum(b)

55.0

In [ ]:
np.sum(b,axis=0)

array([25., 30.])

In [ ]:
np.sum(b,axis=1)

array([ 3.,  7., 11., 15., 19.])

In [ ]:
np.mean(b)

5.5

In [ ]:
np.mean(b,axis=0)

array([5., 6.])

In [ ]:
np.mean(b,axis=1)

array([1.5, 3.5, 5.5, 7.5, 9.5])

In [ ]:
np.median(b,axis=1)

array([1.5, 3.5, 5.5, 7.5, 9.5])

In [ ]:
np.median(b)

5.5

In [ ]:
np.std(b)

2.8722813232690143

In [ ]:
#zero
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
b=np.identity(4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
b.T

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
na=np.array([[4,5,6,7],[5,6,7,4]])
na.T

array([[4, 5],
       [5, 6],
       [6, 7],
       [7, 4]])

In [ ]:
l=[3,3,3,4,5,3,2,5]
np.unique(l)

array([2, 3, 4, 5])

In [ ]:
np.sort(l)

array([2, 3, 3, 3, 3, 4, 5, 5])

In [ ]:
#array indexing
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[0]

1

In [ ]:
arr[0:3]

array([1, 2, 3])

In [ ]:
arr[0]+arr[3]

5

In [ ]:
arr1=np.array([[2,3,4,5],[3,4,5,6]])
arr1

array([[2, 3, 4, 5],
       [3, 4, 5, 6]])

In [ ]:
arr1.ndim

2

In [ ]:
#arr1[1,3]
arr1[0][2]

4

In [ ]:
arr1[0][-1]

5

In [ ]:
arr1[0][::-1]

array([5, 4, 3, 2])

In [ ]:
#pandas - pandas is one the python data analysis,data wrangling package,
# data cleaning
#data structure
#data aggregation
#data analysis
#data manipulation and so much of data exploration like visualization

#Data Structure

#panda series


import pandas as pd
x=[3,4,5,7]
d=pd.Series(x)
d


0    3
1    4
2    5
3    7
dtype: int64

In [ ]:
e={'a':1,'b':2,'c':3}
f=pd.Series(e)
f

a    1
b    2
c    3
dtype: int64

In [ ]:
a={'one':2,'two':4,'three':6}
pd.Series(a)

one      2
two      4
three    6
dtype: int64

In [ ]:
web={'visitors':[200,300,400,500],'day':[1,2,3,4],'bounce':[100,200,100,50]}
df=pd.DataFrame(web)
df

visitors  day  bounce
0       200    1     100
1       300    2     200
2       400    3     100
3       500    4      50

In [ ]:
df.head(2)

visitors  day  bounce
0       200    1     100
1       300    2     200

In [ ]:
df.tail(2)

visitors  day  bounce
2       400    3     100
3       500    4      50

In [ ]:
#access
df['visitors']

0    200
1    300
2    400
3    500
Name: visitors, dtype: int64

In [ ]:
df['visitors'][0:1]

0    200
Name: visitors, dtype: int64

In [ ]:
# prompt: 2d dimension dictionary for 4 persons name,age,city
data = {
    'person1': {'name': 'Alice', 'age': 30, 'city': 'New York'},
    'person2': {'name': 'Bob', 'age': 25, 'city': 'London'},
    'person3': {'name': 'Charlie', 'age': 35, 'city': 'Paris'},
    'person4': {'name': 'David', 'age': 28, 'city': 'Tokyo'}
}

print(data)
print(data['person1']['name'])
print(data['person3']['city'])

{'name': 'Alice', 'age': 20, 'courses': {'math': 90, 'science': 85, 'history': 92}}
85


In [ ]:
data

{'name': 'Alice',
 'age': 20,
 'courses': {'math': 90, 'science': 85, 'history': 92}}

In [ ]:
df=pd.DataFrame(data)
df

name  age  courses
math     Alice   20       90
science  Alice   20       85
history  Alice   20       92

In [ ]:
df.to_csv('data.csv')

In [ ]:
data=pd.read_csv('diabetes.csv')
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
data.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [ ]:
data.shape

(768, 9)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [ ]:
data['Pregnancies']

0       6
1       1
2       8
3       1
4       0
       ..
763    10
764     2
765     5
766     1
767     1
Name: Pregnancies, Length: 768, dtype: int64

In [ ]:
data['Pregnancies'][0:5]

0    6
1    1
2    8
3    1
4    0
Name: Pregnancies, dtype: int64

In [ ]:
data[['Pregnancies','Glucose']][0:5] # method one

Pregnancies  Glucose
0            6      148
1            1       85
2            8      183
3            1       89
4            0      137

In [ ]:
# method 2 using i loc

data.iloc[:,0:2]

Pregnancies  Glucose
0              6      148
1              1       85
2              8      183
3              1       89
4              0      137
..           ...      ...
763           10      101
764            2      122
765            5      121
766            1      126
767            1       93

[768 rows x 2 columns]

In [ ]:
data.iloc[0:5,0:2]

Pregnancies  Glucose
0            6      148
1            1       85
2            8      183
3            1       89
4            0      137

In [ ]:
data['Pregnancies'].mean()

np.float64(3.8450520833333335)

In [ ]:
data.groupby('Pregnancies').mean()

Glucose  BloodPressure  SkinThickness     Insulin        BMI  \
Pregnancies                                                                    
0            123.000000      67.153153      22.270270   81.675676  34.290090   
1            112.748148      67.792593      24.437037   98.674074  31.372593   
2            110.796117      63.252427      21.601942   85.844660  30.583495   
3            123.586667      66.586667      20.080000   87.453333  30.425333   
4            125.117647      70.029412      15.882353   69.441176  32.141176   
5            118.859649      76.210526      17.385965   57.298246  33.192982   
6            120.800000      68.420000      17.640000   63.580000  30.290000   
7            136.444444      70.777778      20.288889   84.466667  32.631111   
8            131.736842      75.184211      17.315789   92.815789  31.568421   
9            131.392857      77.892857      20.892857   62.428571  31.707143   
10           120.916667      70.208333      15.708333   34.791667  30.641667   
11           126.454545      74.181818      21.727273   65.454545  38.563636   
12           113.555556      76.333333      27.111111  112.555556  32.344444   
13           125.500000      73.800000      17.300000   27.900000  35.000000   
14           137.500000      70.000000      27.500000   92.000000  35.100000   
15           136.000000      70.000000      32.000000  110.000000  37.100000   
17           163.000000      72.000000      41.000000  114.000000  40.900000   

             DiabetesPedigreeFunction        Age   Outcome  
Pregnancies                                                 
0                            0.520838  27.603604  0.342342  
1                            0.486496  27.370370  0.214815  
2                            0.491660  27.194175  0.184466  
3                            0.432147  29.026667  0.360000  
4                            0.446353  32.779412  0.338235  
5                            0.396421  39.035088  0.368421  
6                            0.429520  39.340000  0.320000  
7                            0.443622  41.111111  0.555556  
8                            0.504711  45.368421  0.578947  
9                            0.550679  44.178571  0.642857  
10                           0.454167  42.666667  0.416667  
11                           0.522545  44.545455  0.636364  
12                           0.444333  47.444444  0.444444  
13                           0.463300  44.500000  0.500000  
14                           0.312000  42.000000  1.000000  
15                           0.153000  43.000000  1.000000  
17                           0.817000  47.000000  1.000000

In [ ]:
data.groupby('Pregnancies').count()

Glucose  BloodPressure  SkinThickness  Insulin  BMI  \
Pregnancies                                                        
0                111            111            111      111  111   
1                135            135            135      135  135   
2                103            103            103      103  103   
3                 75             75             75       75   75   
4                 68             68             68       68   68   
5                 57             57             57       57   57   
6                 50             50             50       50   50   
7                 45             45             45       45   45   
8                 38             38             38       38   38   
9                 28             28             28       28   28   
10                24             24             24       24   24   
11                11             11             11       11   11   
12                 9              9              9        9    9   
13                10             10             10       10   10   
14                 2              2              2        2    2   
15                 1              1              1        1    1   
17                 1              1              1        1    1   

             DiabetesPedigreeFunction  Age  Outcome  
Pregnancies                                          
0                                 111  111      111  
1                                 135  135      135  
2                                 103  103      103  
3                                  75   75       75  
4                                  68   68       68  
5                                  57   57       57  
6                                  50   50       50  
7                                  45   45       45  
8                                  38   38       38  
9                                  28   28       28  
10                                 24   24       24  
11                                 11   11       11  
12                                  9    9        9  
13                                 10   10       10  
14                                  2    2        2  
15                                  1    1        1  
17                                  1    1        1

In [ ]:
data.groupby('Outcome').count()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI  \
Outcome                                                                     
0                500      500            500            500      500  500   
1                268      268            268            268      268  268   

         DiabetesPedigreeFunction  Age  
Outcome                                 
0                             500  500  
1                             268  268

In [ ]:
data.groupby('Outcome').mean()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
Outcome                                                                      
0           3.298000  109.980000      68.184000      19.664000   68.792000   
1           4.865672  141.257463      70.824627      22.164179  100.335821   

               BMI  DiabetesPedigreeFunction        Age  
Outcome                                                  
0        30.304200                  0.429734  31.190000  
1        35.142537                  0.550500  37.067164